### ISSUE TITLE
[Refactor] Rewrite code and functions with proper Karlsen naming.

### ISSUE THREAD

**Issue by lemois-1337** [karlsen-network/karlsen-miner#1]
Perform a code rebase and update function names by applying the following prefixes or suffixes:

1. Replace `kas` with `kls`
2. Replace `kaspa` with `karlsen`

Ensure these changes are applied to upper, lower, and mixed cases. Additionally, update the required ports in both the code and documentation:

- RPC: Change from `16110` to `42110`
- P2P: Change from `16111` to `42111`

The primary objective of this refactoring is to create a `karlsen-miner` without any references to Kaspa. It's essential to address RPC calls still named `kaspa`, and these will be modified during the `karlsend` refactoring. This adjustment is a relatively straightforward fix and presents a valuable opportunity for contributors to engage, learn, and contribute to the codebase.

**Comment by RoboticWF** [comment]
Will have PR for this shortly

**Comment by RoboticWF** [comment]
PR is ready here: https://github.com/karlsen-network/karlsen-miner/pull/3

**Comment by Leon1777** [comment]
@lemois-1337 this can also be closed as it was addressed with https://github.com/karlsen-network/karlsen-miner/pull/6
